version: '2'
services:
  postgresql:
  
    restart: unless-stopped
    image: docker.io/bitnami/postgresql:13
    volumes:
      - 'postgresql_data:/bitnami/postgresql'
    environment:
      #Dejar solo en blanco para dev
      - ALLOW_EMPTY_PASSWORD=yes
      - POSTGRESQL_USERNAME=bn_odoo
      - POSTGRESQL_DATABASE=bitnami_odoo
  odoo:
  
    restart: unless-stopped
    image: docker.io/bitnami/odoo:15
    ports:
      #cambiar el puerto al que se liga en la maquina, estoy designando un puero diferente para no modificar el nginx
      - '8069:8069'
      #normalmente se maneja el puerto 80 para no afectar cuando solo se utiliza la imagen sin nginx
      #lalito modifique esta parte para que peudas agregar el repo en local del enterprise
      #mira, comienzas creando una carpeta que se va a llamar addons, no te preocupes va a ser en la misma carpeta donde pongas 
      #este doicumento yamel, 
      #en la carpeta va a agregar todos los modulos que quieras, no dentro de carpetas
      #los agregas sueltos, lo hice en rapido sowi.
      #en esta carpeta agregas el enterprise. y cuando lo corras ya lo va a tener.
      #asi como cualquier cosa de la oca
      #ademas puedes modificar codigo
    volumes:
      - 'odoo_data:/bitnami/odoo'
      - './addons:/bitnami/odoo/addons'
    depends_on:
      - postgresql
    environment:
      #Dejar solo en blanco para dev
      - ALLOW_EMPTY_PASSWORD=yes
      - ODOO_DATABASE_HOST=postgresql
      - ODOO_DATABASE_PORT_NUMBER=5432
      - ODOO_DATABASE_USER=bn_odoo
      - ODOO_DATABASE_NAME=bitnami_odoo








  app:
    image: 'jc21/nginx-proxy-manager:latest'
    ports:
      - '80:80'
      - '81:81'
      - '443:443'
    environment:
      DB_MYSQL_HOST: "db"
      DB_MYSQL_PORT: 3306
      DB_MYSQL_USER: "npm"
      DB_MYSQL_PASSWORD: "npm"
      DB_MYSQL_NAME: "npm"
    volumes:
      - ./data:/data
      - ./letsencrypt:/etc/letsencrypt
  db:
    image: 'jc21/mariadb-aria:latest'
    environment:
      MYSQL_ROOT_PASSWORD: 'npm'
      MYSQL_DATABASE: 'npm'
      MYSQL_USER: 'npm'
      MYSQL_PASSWORD: 'npm'
    volumes:
      - 'mysql:/var/lib/mysql'


volumes:
  postgresql_data:
    driver: local
  odoo_data:
    driver: local
  mysql:
    driver: local
